// Code generated by gen/z80/fuse_tests. DO NOT EDIT.

package z80

import "github.com/blackchip-org/pac8/memory"

var fuseTests = []fuseTest{
	fuseTest{
		name:    "78",
		af:      0x0200,
		bc:      0xcf98,
		de:      0x90d8,
		hl:      0xa169,
		af1:     0x0000,
		bc1:     0x0000,
		de1:     0x0000,
		hl1:     0x0000,
		ix:      0x0000,
		iy:      0x0000,
		sp:      0x0000,
		pc:      0x0000,
		i:       0x00,
		r:       0x00,
		iff1:    0,
		iff2:    0,
		halt:    0,
		tstates: 1,
		snapshots: []memory.Snapshot{
			memory.Snapshot{Address: 0x0000, Values: []uint8{0x78}},
			memory.Snapshot{Address: 0xa169, Values: []uint8{0x50}},
		},
	},
}

var fuseResults = map[string]fuseTest{
	"78": fuseTest{
		name:      "78",
		af:        0xcf00,
		bc:        0xcf98,
		de:        0x90d8,
		hl:        0xa169,
		af1:       0x0000,
		bc1:       0x0000,
		de1:       0x0000,
		hl1:       0x0000,
		ix:        0x0000,
		iy:        0x0000,
		sp:        0x0000,
		pc:        0x0001,
		i:         0x00,
		r:         0x01,
		iff1:      0,
		iff2:      0,
		halt:      0,
		tstates:   4,
		snapshots: []memory.Snapshot{},
	},
}
