// Code generated by cpu/z80/dasm/gen.go. DO NOT EDIT.

package z80

type harstonTest struct {
	name  string
	op    string
	bytes []uint8
}

var harstonTests = []harstonTest{
	harstonTest{"00", "nop", []uint8{0x00}},
	harstonTest{"01 34 12", "ld   bc,$1234", []uint8{0x01, 0x34, 0x12}},
	harstonTest{"02", "ld   (bc),a", []uint8{0x02}},
	harstonTest{"03", "inc  bc", []uint8{0x03}},
	harstonTest{"04", "inc  b", []uint8{0x04}},
	harstonTest{"05", "dec  b", []uint8{0x05}},
	harstonTest{"06 12", "ld   b,$12", []uint8{0x06, 0x12}},
	harstonTest{"07", "rlca", []uint8{0x07}},
	harstonTest{"08", "ex   af,af'", []uint8{0x08}},
	harstonTest{"09", "add  hl,bc", []uint8{0x09}},
	harstonTest{"0a", "ld   a,(bc)", []uint8{0x0a}},
	harstonTest{"0b", "dec  bc", []uint8{0x0b}},
	harstonTest{"0c", "inc  c", []uint8{0x0c}},
	harstonTest{"0d", "dec  c", []uint8{0x0d}},
	harstonTest{"0e 12", "ld   c,$12", []uint8{0x0e, 0x12}},
	harstonTest{"0f", "rrca", []uint8{0x0f}},
	harstonTest{"10 10", "djnz $0020", []uint8{0x10, 0x10}},
	harstonTest{"11 34 12", "ld   de,$1234", []uint8{0x11, 0x34, 0x12}},
	harstonTest{"12", "ld   (de),a", []uint8{0x12}},
	harstonTest{"13", "inc  de", []uint8{0x13}},
	harstonTest{"14", "inc  d", []uint8{0x14}},
	harstonTest{"15", "dec  d", []uint8{0x15}},
	harstonTest{"16 12", "ld   d,$12", []uint8{0x16, 0x12}},
	harstonTest{"17", "rla", []uint8{0x17}},
	harstonTest{"18 10", "jr   $0020", []uint8{0x18, 0x10}},
	harstonTest{"19", "add  hl,de", []uint8{0x19}},
	harstonTest{"1a", "ld   a,(de)", []uint8{0x1a}},
	harstonTest{"1b", "dec  de", []uint8{0x1b}},
	harstonTest{"1c", "inc  e", []uint8{0x1c}},
	harstonTest{"1d", "dec  e", []uint8{0x1d}},
	harstonTest{"1e 12", "ld   e,$12", []uint8{0x1e, 0x12}},
	harstonTest{"1f", "rra", []uint8{0x1f}},
	harstonTest{"20 10", "jr   nz,$0020", []uint8{0x20, 0x10}},
	harstonTest{"21 34 12", "ld   hl,$1234", []uint8{0x21, 0x34, 0x12}},
	harstonTest{"22 34 12", "ld   ($1234),hl", []uint8{0x22, 0x34, 0x12}},
}
